// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: pb/osmoxy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_osmoxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_osmoxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_pb_osmoxy_proto_rawDescGZIP(), []int{0}
}

type PoolAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Denom  string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Weight string `protobuf:"bytes,3,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *PoolAsset) Reset() {
	*x = PoolAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_osmoxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolAsset) ProtoMessage() {}

func (x *PoolAsset) ProtoReflect() protoreflect.Message {
	mi := &file_pb_osmoxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolAsset.ProtoReflect.Descriptor instead.
func (*PoolAsset) Descriptor() ([]byte, []int) {
	return file_pb_osmoxy_proto_rawDescGZIP(), []int{1}
}

func (x *PoolAsset) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *PoolAsset) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PoolAsset) GetWeight() string {
	if x != nil {
		return x.Weight
	}
	return ""
}

type Pool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index  string       `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Assets []*PoolAsset `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	Fee    string       `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (x *Pool) Reset() {
	*x = Pool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_osmoxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_pb_osmoxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_pb_osmoxy_proto_rawDescGZIP(), []int{2}
}

func (x *Pool) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *Pool) GetAssets() []*PoolAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *Pool) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

type PoolsSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNumber uint64  `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Pools       []*Pool `protobuf:"bytes,2,rep,name=pools,proto3" json:"pools,omitempty"`
}

func (x *PoolsSnapshot) Reset() {
	*x = PoolsSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_osmoxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolsSnapshot) ProtoMessage() {}

func (x *PoolsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pb_osmoxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolsSnapshot.ProtoReflect.Descriptor instead.
func (*PoolsSnapshot) Descriptor() ([]byte, []int) {
	return file_pb_osmoxy_proto_rawDescGZIP(), []int{3}
}

func (x *PoolsSnapshot) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *PoolsSnapshot) GetPools() []*Pool {
	if x != nil {
		return x.Pools
	}
	return nil
}

type PoolUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index  string       `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Assets []*PoolAsset `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
}

func (x *PoolUpdate) Reset() {
	*x = PoolUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_osmoxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolUpdate) ProtoMessage() {}

func (x *PoolUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_osmoxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolUpdate.ProtoReflect.Descriptor instead.
func (*PoolUpdate) Descriptor() ([]byte, []int) {
	return file_pb_osmoxy_proto_rawDescGZIP(), []int{4}
}

func (x *PoolUpdate) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *PoolUpdate) GetAssets() []*PoolAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type PoolsUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromBlockNumber uint64        `protobuf:"varint,1,opt,name=from_block_number,json=fromBlockNumber,proto3" json:"from_block_number,omitempty"`
	ToBlockNumber   uint64        `protobuf:"varint,2,opt,name=to_block_number,json=toBlockNumber,proto3" json:"to_block_number,omitempty"`
	Timestamp       uint64        `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Updates         []*PoolUpdate `protobuf:"bytes,4,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *PoolsUpdate) Reset() {
	*x = PoolsUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_osmoxy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolsUpdate) ProtoMessage() {}

func (x *PoolsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_osmoxy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolsUpdate.ProtoReflect.Descriptor instead.
func (*PoolsUpdate) Descriptor() ([]byte, []int) {
	return file_pb_osmoxy_proto_rawDescGZIP(), []int{5}
}

func (x *PoolsUpdate) GetFromBlockNumber() uint64 {
	if x != nil {
		return x.FromBlockNumber
	}
	return 0
}

func (x *PoolsUpdate) GetToBlockNumber() uint64 {
	if x != nil {
		return x.ToBlockNumber
	}
	return 0
}

func (x *PoolsUpdate) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PoolsUpdate) GetUpdates() []*PoolUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type UniV2Pair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PairAddress string `protobuf:"bytes,1,opt,name=pair_address,json=pairAddress,proto3" json:"pair_address,omitempty"`
	Token0      string `protobuf:"bytes,2,opt,name=token0,proto3" json:"token0,omitempty"`
	Token1      string `protobuf:"bytes,3,opt,name=token1,proto3" json:"token1,omitempty"`
	Reserve0    string `protobuf:"bytes,4,opt,name=reserve0,proto3" json:"reserve0,omitempty"`
	Reserve1    string `protobuf:"bytes,5,opt,name=reserve1,proto3" json:"reserve1,omitempty"`
	FeeRev      uint32 `protobuf:"varint,6,opt,name=fee_rev,json=feeRev,proto3" json:"fee_rev,omitempty"`
}

func (x *UniV2Pair) Reset() {
	*x = UniV2Pair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_osmoxy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniV2Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniV2Pair) ProtoMessage() {}

func (x *UniV2Pair) ProtoReflect() protoreflect.Message {
	mi := &file_pb_osmoxy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniV2Pair.ProtoReflect.Descriptor instead.
func (*UniV2Pair) Descriptor() ([]byte, []int) {
	return file_pb_osmoxy_proto_rawDescGZIP(), []int{6}
}

func (x *UniV2Pair) GetPairAddress() string {
	if x != nil {
		return x.PairAddress
	}
	return ""
}

func (x *UniV2Pair) GetToken0() string {
	if x != nil {
		return x.Token0
	}
	return ""
}

func (x *UniV2Pair) GetToken1() string {
	if x != nil {
		return x.Token1
	}
	return ""
}

func (x *UniV2Pair) GetReserve0() string {
	if x != nil {
		return x.Reserve0
	}
	return ""
}

func (x *UniV2Pair) GetReserve1() string {
	if x != nil {
		return x.Reserve1
	}
	return ""
}

func (x *UniV2Pair) GetFeeRev() uint32 {
	if x != nil {
		return x.FeeRev
	}
	return 0
}

type UniV2PairsSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNumber uint64       `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Pairs       []*UniV2Pair `protobuf:"bytes,2,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (x *UniV2PairsSnapshot) Reset() {
	*x = UniV2PairsSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_osmoxy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniV2PairsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniV2PairsSnapshot) ProtoMessage() {}

func (x *UniV2PairsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pb_osmoxy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniV2PairsSnapshot.ProtoReflect.Descriptor instead.
func (*UniV2PairsSnapshot) Descriptor() ([]byte, []int) {
	return file_pb_osmoxy_proto_rawDescGZIP(), []int{7}
}

func (x *UniV2PairsSnapshot) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *UniV2PairsSnapshot) GetPairs() []*UniV2Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type UniV2PairUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PairAddress string `protobuf:"bytes,1,opt,name=pair_address,json=pairAddress,proto3" json:"pair_address,omitempty"`
	Reserve0    string `protobuf:"bytes,2,opt,name=reserve0,proto3" json:"reserve0,omitempty"`
	Reserve1    string `protobuf:"bytes,3,opt,name=reserve1,proto3" json:"reserve1,omitempty"`
}

func (x *UniV2PairUpdate) Reset() {
	*x = UniV2PairUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_osmoxy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniV2PairUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniV2PairUpdate) ProtoMessage() {}

func (x *UniV2PairUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_osmoxy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniV2PairUpdate.ProtoReflect.Descriptor instead.
func (*UniV2PairUpdate) Descriptor() ([]byte, []int) {
	return file_pb_osmoxy_proto_rawDescGZIP(), []int{8}
}

func (x *UniV2PairUpdate) GetPairAddress() string {
	if x != nil {
		return x.PairAddress
	}
	return ""
}

func (x *UniV2PairUpdate) GetReserve0() string {
	if x != nil {
		return x.Reserve0
	}
	return ""
}

func (x *UniV2PairUpdate) GetReserve1() string {
	if x != nil {
		return x.Reserve1
	}
	return ""
}

type UniV2PairsUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromBlockNumber uint64             `protobuf:"varint,1,opt,name=from_block_number,json=fromBlockNumber,proto3" json:"from_block_number,omitempty"`
	ToBlockNumber   uint64             `protobuf:"varint,2,opt,name=to_block_number,json=toBlockNumber,proto3" json:"to_block_number,omitempty"`
	Timestamp       uint64             `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Univ2Updates    []*UniV2PairUpdate `protobuf:"bytes,4,rep,name=univ2_updates,json=univ2Updates,proto3" json:"univ2_updates,omitempty"`
}

func (x *UniV2PairsUpdate) Reset() {
	*x = UniV2PairsUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_osmoxy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniV2PairsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniV2PairsUpdate) ProtoMessage() {}

func (x *UniV2PairsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_osmoxy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniV2PairsUpdate.ProtoReflect.Descriptor instead.
func (*UniV2PairsUpdate) Descriptor() ([]byte, []int) {
	return file_pb_osmoxy_proto_rawDescGZIP(), []int{9}
}

func (x *UniV2PairsUpdate) GetFromBlockNumber() uint64 {
	if x != nil {
		return x.FromBlockNumber
	}
	return 0
}

func (x *UniV2PairsUpdate) GetToBlockNumber() uint64 {
	if x != nil {
		return x.ToBlockNumber
	}
	return 0
}

func (x *UniV2PairsUpdate) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UniV2PairsUpdate) GetUniv2Updates() []*UniV2PairUpdate {
	if x != nil {
		return x.Univ2Updates
	}
	return nil
}

var File_pb_osmoxy_proto protoreflect.FileDescriptor

var file_pb_osmoxy_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x6f, 0x73, 0x6d, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x6f, 0x73, 0x6d, 0x6f, 0x78, 0x79, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x09, 0x50, 0x6f, 0x6f,
	0x6c, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x59, 0x0a, 0x04,
	0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x29, 0x0a, 0x06, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x73, 0x6d,
	0x6f, 0x78, 0x79, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x06, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x66, 0x65, 0x65, 0x22, 0x56, 0x0a, 0x0d, 0x50, 0x6f, 0x6f, 0x6c, 0x73,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x05, 0x70,
	0x6f, 0x6f, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6f, 0x73, 0x6d,
	0x6f, 0x78, 0x79, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x05, 0x70, 0x6f, 0x6f, 0x6c, 0x73, 0x22,
	0x4d, 0x0a, 0x0a, 0x50, 0x6f, 0x6f, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x29, 0x0a, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x73, 0x6d, 0x6f, 0x78, 0x79, 0x2e, 0x50, 0x6f, 0x6f,
	0x6c, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x22, 0xad,
	0x01, 0x0a, 0x0b, 0x50, 0x6f, 0x6f, 0x6c, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2a,
	0x0a, 0x11, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x66, 0x72, 0x6f, 0x6d, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x6f,
	0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0d, 0x74, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x2c, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x73, 0x6d, 0x6f, 0x78, 0x79, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x22, 0xaf,
	0x01, 0x0a, 0x09, 0x55, 0x6e, 0x69, 0x56, 0x32, 0x50, 0x61, 0x69, 0x72, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x61, 0x69, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x69, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x30, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x30, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x31, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x31, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x65, 0x65, 0x5f, 0x72,
	0x65, 0x76, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x66, 0x65, 0x65, 0x52, 0x65, 0x76,
	0x22, 0x60, 0x0a, 0x12, 0x55, 0x6e, 0x69, 0x56, 0x32, 0x50, 0x61, 0x69, 0x72, 0x73, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x05, 0x70, 0x61, 0x69,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x73, 0x6d, 0x6f, 0x78,
	0x79, 0x2e, 0x55, 0x6e, 0x69, 0x56, 0x32, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69,
	0x72, 0x73, 0x22, 0x6c, 0x0a, 0x0f, 0x55, 0x6e, 0x69, 0x56, 0x32, 0x50, 0x61, 0x69, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x69, 0x72, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x69,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x30, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x30, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x31,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x31,
	0x22, 0xc2, 0x01, 0x0a, 0x10, 0x55, 0x6e, 0x69, 0x56, 0x32, 0x50, 0x61, 0x69, 0x72, 0x73, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0f, 0x66, 0x72, 0x6f, 0x6d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x6f, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x74, 0x6f, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x3c, 0x0a, 0x0d, 0x75, 0x6e, 0x69, 0x76, 0x32,
	0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x6f, 0x73, 0x6d, 0x6f, 0x78, 0x79, 0x2e, 0x55, 0x6e, 0x69, 0x56, 0x32, 0x50, 0x61, 0x69,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x75, 0x6e, 0x69, 0x76, 0x32, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x32, 0xb0, 0x02, 0x0a, 0x06, 0x4f, 0x73, 0x6d, 0x6f, 0x78, 0x79,
	0x12, 0x41, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x73, 0x53, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x12, 0x14, 0x2e, 0x6f, 0x73, 0x6d, 0x6f, 0x78, 0x79, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6f, 0x73, 0x6d,
	0x6f, 0x78, 0x79, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x73, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x50, 0x6f, 0x6f, 0x6c, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x6f, 0x73,
	0x6d, 0x6f, 0x78, 0x79, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x6f, 0x73, 0x6d, 0x6f, 0x78, 0x79, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4b, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x55, 0x6e, 0x69, 0x56, 0x32, 0x50, 0x61, 0x69, 0x72, 0x73, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x14, 0x2e, 0x6f, 0x73, 0x6d, 0x6f, 0x78, 0x79, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6f, 0x73, 0x6d, 0x6f,
	0x78, 0x79, 0x2e, 0x55, 0x6e, 0x69, 0x56, 0x32, 0x50, 0x61, 0x69, 0x72, 0x73, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x19, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x55, 0x6e, 0x69, 0x56, 0x32, 0x50, 0x61, 0x69, 0x72, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x6f, 0x73, 0x6d, 0x6f, 0x78, 0x79, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6f, 0x73, 0x6d,
	0x6f, 0x78, 0x79, 0x2e, 0x55, 0x6e, 0x69, 0x56, 0x32, 0x50, 0x61, 0x69, 0x72, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_osmoxy_proto_rawDescOnce sync.Once
	file_pb_osmoxy_proto_rawDescData = file_pb_osmoxy_proto_rawDesc
)

func file_pb_osmoxy_proto_rawDescGZIP() []byte {
	file_pb_osmoxy_proto_rawDescOnce.Do(func() {
		file_pb_osmoxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_osmoxy_proto_rawDescData)
	})
	return file_pb_osmoxy_proto_rawDescData
}

var file_pb_osmoxy_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_osmoxy_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil),       // 0: osmoxy.EmptyRequest
	(*PoolAsset)(nil),          // 1: osmoxy.PoolAsset
	(*Pool)(nil),               // 2: osmoxy.Pool
	(*PoolsSnapshot)(nil),      // 3: osmoxy.PoolsSnapshot
	(*PoolUpdate)(nil),         // 4: osmoxy.PoolUpdate
	(*PoolsUpdate)(nil),        // 5: osmoxy.PoolsUpdate
	(*UniV2Pair)(nil),          // 6: osmoxy.UniV2Pair
	(*UniV2PairsSnapshot)(nil), // 7: osmoxy.UniV2PairsSnapshot
	(*UniV2PairUpdate)(nil),    // 8: osmoxy.UniV2PairUpdate
	(*UniV2PairsUpdate)(nil),   // 9: osmoxy.UniV2PairsUpdate
}
var file_pb_osmoxy_proto_depIdxs = []int32{
	1,  // 0: osmoxy.Pool.assets:type_name -> osmoxy.PoolAsset
	2,  // 1: osmoxy.PoolsSnapshot.pools:type_name -> osmoxy.Pool
	1,  // 2: osmoxy.PoolUpdate.assets:type_name -> osmoxy.PoolAsset
	4,  // 3: osmoxy.PoolsUpdate.updates:type_name -> osmoxy.PoolUpdate
	6,  // 4: osmoxy.UniV2PairsSnapshot.pairs:type_name -> osmoxy.UniV2Pair
	8,  // 5: osmoxy.UniV2PairsUpdate.univ2_updates:type_name -> osmoxy.UniV2PairUpdate
	0,  // 6: osmoxy.Osmoxy.GetPoolsSnapshot:input_type -> osmoxy.EmptyRequest
	0,  // 7: osmoxy.Osmoxy.SubscribePoolsUpdate:input_type -> osmoxy.EmptyRequest
	0,  // 8: osmoxy.Osmoxy.GetUniV2PairsSnapshot:input_type -> osmoxy.EmptyRequest
	0,  // 9: osmoxy.Osmoxy.SubscribeUniV2PairsUpdate:input_type -> osmoxy.EmptyRequest
	3,  // 10: osmoxy.Osmoxy.GetPoolsSnapshot:output_type -> osmoxy.PoolsSnapshot
	5,  // 11: osmoxy.Osmoxy.SubscribePoolsUpdate:output_type -> osmoxy.PoolsUpdate
	7,  // 12: osmoxy.Osmoxy.GetUniV2PairsSnapshot:output_type -> osmoxy.UniV2PairsSnapshot
	9,  // 13: osmoxy.Osmoxy.SubscribeUniV2PairsUpdate:output_type -> osmoxy.UniV2PairsUpdate
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pb_osmoxy_proto_init() }
func file_pb_osmoxy_proto_init() {
	if File_pb_osmoxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_osmoxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_osmoxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_osmoxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_osmoxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolsSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_osmoxy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_osmoxy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolsUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_osmoxy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniV2Pair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_osmoxy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniV2PairsSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_osmoxy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniV2PairUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_osmoxy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniV2PairsUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_osmoxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_osmoxy_proto_goTypes,
		DependencyIndexes: file_pb_osmoxy_proto_depIdxs,
		MessageInfos:      file_pb_osmoxy_proto_msgTypes,
	}.Build()
	File_pb_osmoxy_proto = out.File
	file_pb_osmoxy_proto_rawDesc = nil
	file_pb_osmoxy_proto_goTypes = nil
	file_pb_osmoxy_proto_depIdxs = nil
}
